### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by bjorndaniel**

### CODE REVIEW

**Comment by sthewissen** [comment]
Awesome! Could I trouble you for 3 more texts that I forgot? 

"Sign in"
"Swipe to continue"
"Try with a demo account"

Feel free to leave the translations here and I'll make sure they make their way in :)

**Comment by bjorndaniel** [comment]
Absolutely! :
Sign in - Logga in
Swipe to continue - Svep för att gå vidare
Try with a demo account - Prova med ett demokonto

**Comment by sthewissen** [comment]
Thanks! I added those 3 in. I also had someone else respond that he wanted to do Swedish, so I asked him to review this PR. That way at least 2 people have looked at it and we can merge this once the review is done 👍 

Thanks for the effort so far!

**Comment by bjorndaniel** [comment]
That is great, there are a couple I was not 100% happy with, so it would be nice to have a second opinion!

**Review by carlwilke — COMMENTED** [review]
Translation into Swedish reviewed, I agree with the language and terms used by the translator

**Comment by sthewissen** [comment]
Then I'll merge it in a bit, add credits for you both in the app and we'll be off to the races! Thanks a lot again!

**Pull request merged**
