### PR TITLE
Hungarian translations

### PR DESCRIPTION
**Pull request by mkanyo**
Having added language_hungarian to the main Translations.resx it my VS regenerated the Translations.Designer.cs in a slightly different format than yours. Not sure why I am running the latest VS Professional 16.8.3

### CODE REVIEW

**Comment by sthewissen** [comment]
Awesome! Could I trouble you for 3 more texts that I forgot? 

"Sign in"
"Swipe to continue"
"Try with a demo account"

Feel free to leave the translations here and I'll make sure they make their way in :)

**Comment by mkanyo** [comment]
> Awesome! Could I trouble you for 3 more texts that I forgot?
> 
> "Sign in"
> "Swipe to continue"
> "Try with a demo account"
> 
> Feel free to leave the translations here and I'll make sure they make their way in :)

Sure, glad I could help 👍 

"Sign in" - "Bejelentkezés"
"Swipe to continue" - "Legyints a folytatáshoz"
"Try with a demo account" - "Kipróbálom próba fiókkal"

But if you got more coming let me know, I'll try to rebase and update my commit.

**Comment by sthewissen** [comment]
Awesome! I already did some changes on your branch, but rebasing on current main should pull in the three additional labels:

```
    <data name="sign_in" xml:space="preserve">
        <value>Sign in</value>
    </data>
    <data name="swipe_to_continue" xml:space="preserve">
        <value>Swipe to continue</value>
    </data>
    <data name="try_with_demo_account" xml:space="preserve">
        <value>Try with a demo account</value>
    </data>
```

**Comment by sthewissen** [comment]
Consider this merged and your name added to the in-app Hall of Fame! Big thanks!

image

**Comment by mkanyo** [comment]
Ah, that's really cool, thanks man! 🙂  Glad I could help, Miklos

**Pull request merged**
