### PR TITLE
Created main.yml file to setup GitHub Action

### PR DESCRIPTION
**Pull request by saamerm**
Created main.yml file to setup GitHub Action

* Added main.yml file that orders 2 jobs on every push and merge request
* One job is to build iOS and the other builds Android

**Purpose of Action**
-----
* The action performs a sanity test on your apps— makes sure the iOS & Android apps build on each commit or merge request, ensuring that there is no bug introduced in that commit
* More details in [the article](https://medium.com/@prototypemakers/using-github-actions-with-ios-and-android-xamarin-apps-693a93b48a61) or the corresponding [unmetered article link](https://medium.com/@prototypemakers/using-github-actions-with-ios-and-android-xamarin-apps-693a93b48a61?sk=cd81773f2e5a5931ae49c9362b4db795)

**Testing**
--------
* Tested the Action on [my fork](https://github.com/saamerm/MVP/commit/df5f9ecbd8815420c0efff9e8739bb243ce43311/checks?check_suite_id=396814598) and it passed the tests

### CODE REVIEW

**Comment by saamerm** [comment]
Woot woot thank you

**Comment by sthewissen** [comment]
@saamerm I haven't worked with GH Actions yet, so I might be asking a dumb question, but can something be done about the iOS build failing because it has no provisioning profiles yet? Just for a CI it shouldn't need them, but I'm guessing it's related to building in Release mode?

**Comment by saamerm** [comment]
Hey @sthewissen Yes! I explained it a bit here https://github.com/sthewissen/MVP/pull/13

The GH Action in your repo is a free tool to help make sure that no one breaks the build (Eg: misses a semicolon) in their Pull Request, which is especially helpful with big merge requests, where you want an additional level of check-GH performs a "Rebuild All".

Your iOS csproj file requires additional files in order to build in Release mode, so you were seeing the error. I just removed those build requirements, and so it started working.

The Practice step is not needed at all. It was just introduced to make you more comfortable with using Actions, showing that you can perform multiple mac commands like cd (change directory), ls (list out all the files and directories in that location), and so on. You can see the results of those commands in the output window.

**Comment by sthewissen** [comment]
Awesome!

**Pull request merged**
